### PR TITLE
Up to v0.20.1

### PR DESCRIPTION
**Pull request by alex-w**

### CODE REVIEW

**Comment by plars** [comment]
Thanks for this! I created this snap out of personal interest, but I'd really be interested in seeing if you want to adopt it as an official one and have it be always up-to-date with the latest release.

**Comment by alex-w** [comment]
Seems default snap environment (ubuntu 14.04?) is not acceptable for snap package (see log: modern stellarium required Qt 5.6.0 as minimal version of Qt) :(

Could you looking it for resolve issue (I didn't used and produced snap packages before)?

Adopting your instructions for create snap packages as an official one by us may be very useful for users. What about daily snaps?

**Comment by alex-w** [comment]
the issue has been fixed in this fork: https://github.com/t4saha/stellarium/commits/master

**Comment by plars** [comment]
Great! I merged the version tag bump on Friday and saw something had changed to cause the build to fail, but I haven't had a chance to look at it over the weekend. I was actually hoping to look at it after work today, but I'm always happy when someone beats me to it. :)
It looks like that branch merges puts the snap build pieces in the source repo for stellarium, which may be preferred if you want to make daily builds easier.  Let me know if you want, and I can deprecate mine so that yours is the clear choice for installing from this point on.

**Pull request merged**
